version: '3.7'

services:
  kiwoonapigateway:
    build:
      context: .
      dockerfile: Kiwoon.Gateway/Dockerfile
    ports:
     - '8888:8888'
    environment:
     - ASPNETCORE_URLS=http://+:8888
     - ASPNETCORE_ENVIRONMENT=Development
    env_file:
     - azure.env
  kiwoonaccountms:
    build:
      context: .
      dockerfile: Kiwoon.Accounts/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    env_file:
     - azure.env