version: '3.7'

services:
  kiwoonapi:
    build:
      context: .
      dockerfile: Kiwoon.Core/Dockerfile
    ports:
     - '8888:8888'
    environment:
     - ASPNETCORE_URLS=http://+:8888
     - ASPNETCORE_ENVIRONMENT=Development
    env_file:
     - azure.env
  kiwoonredis:
    container_name: redis
    image: redis:latest